// Batch 2: Menambah beberapa destinasi wisata baru per kabupaten/kota
// (tidak menghapus data lama, hanya menambah agar tiap kabupaten punya banyak pilihan wisata)
db.destinations.insertMany([
  // ===== BULUKUMBA =====
  { name: "Tanjung Bira", slug: "tanjung-bira-bulukumba", category: "Pantai", regency: "Bulukumba",
    description: "Ikon utama wisata Bulukumba dengan pasir putih selembut tepung, air jernih untuk snorkeling dan diving, serta jadi titik penyeberangan ke Pulau Kambing.",
    location: { lat: -5.6206, lng: 120.4722 } /* TERVERIFIKASI - Wikidata Q24882119 */, entryFee: "Rp10.000 per orang", openHours: "24 jam",
    tags: ["pantai", "bira", "snorkeling", "phinisi"] },
  { name: "Pantai Apparalang", slug: "pantai-apparalang-bulukumba", category: "Pantai", regency: "Bulukumba",
    description: "Dijuluki 'Raja Ampat-nya Bulukumba', pantai bertebing karang dengan air biru jernih dan spot foto dramatis dari atas tebing.",
    location: { lat: -5.535, lng: 120.415 } /* Estimasi diperbaiki - Desa Ara, Kec. Bontobahari (dekat Tahura Bontobahari). TODO presisi manual */, entryFee: "Rp10.000 per orang", openHours: "06.00 - 18.00",
    tags: ["pantai", "tebing", "apparalang"] },
  { name: "Pantai Bara", slug: "pantai-bara-bulukumba", category: "Pantai", regency: "Bulukumba",
    description: "Terletak di sebelah Tanjung Bira, menawarkan suasana lebih tenang dengan pasir putih dan air laut yang landai, cocok untuk keluarga.",
    location: { lat: -5.618, lng: 120.448 } /* Estimasi diperbaiki - Desa Bira, ~3km barat Tanjung Bira */, entryFee: "Rp10.000 per orang", openHours: "24 jam",
    tags: ["pantai", "bara"] },
  { name: "Puncak Pua Janggo", slug: "puncak-pua-janggo-bulukumba", category: "Budaya/Sejarah", regency: "Bulukumba",
    description: "Situs bersejarah tempat istirahat pemuka agama Islam Pua Janggo di masa lalu, kini jadi spot foto dengan pemandangan Tanjung Bira dari ketinggian.",
    location: { lat: -5.619, lng: 120.469 } /* Estimasi diperbaiki - Desa Bira, ~200m sebelum Pelabuhan Bira */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["sejarah", "puncak", "bira"] },
  { name: "Pulau Kambing", slug: "pulau-kambing-bulukumba", category: "Pulau", regency: "Bulukumba",
    description: "Pulau kecil sekitar 20 menit naik perahu dari Pantai Bira, terkenal karena gugusan terumbu karang sehat dan spot snorkeling-diving terbaik di Bulukumba.",
    location: { lat: -5.6200, lng: 120.4800 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Sewa perahu, mohon verifikasi ke pengelola", openHours: "06.00 - 17.00",
    tags: ["pulau", "snorkeling", "diving"] },
  { name: "Gua Passohara", slug: "gua-passohara-bulukumba", category: "Karst/Goa", regency: "Bulukumba",
    description: "Gua sepanjang lebih dari seratus meter di Desa Wisata Ara dengan bentukan alam unik dan danau air jernih di dalamnya, cocok untuk susur gua.",
    location: { lat: -5.545, lng: 120.42 } /* Estimasi diperbaiki - dekat Pantai Mandala Ria, Desa Lembanna */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "08.00 - 16.00",
    tags: ["gua", "ara", "petualangan"] },

  // ===== GOWA =====
  { name: "Malino Highland", slug: "malino-highland-gowa", category: "Pegunungan", regency: "Gowa",
    description: "Kawasan wisata dataran tinggi dengan kebun teh hijau, udara sejuk, restoran, penginapan, dan aktivitas berkuda di kaki Gunung Bawakaraeng.",
    location: { lat: -5.2489, lng: 119.8567 } /* TERVERIFIKASI - Wikipedia Malino, Tinggimoncong, Gowa */, entryFee: "Rp50.000 per orang", openHours: "08.00 - 18.00",
    tags: ["pegunungan", "malino", "kebun teh"] },
  { name: "Air Terjun Takapala", slug: "air-terjun-takapala-gowa", category: "Air Terjun", regency: "Gowa",
    description: "Air terjun ikonik setinggi sekitar 109 meter di kawasan Malino dengan debit air deras dan kabut dramatis di sekitarnya.",
    location: { lat: -5.265, lng: 119.885 } /* Estimasi diperbaiki - Kel. Bontolerung, Kec. Tinggimoncong, ~6km dari Malino */, entryFee: "Rp10.000 per orang", openHours: "07.00 - 17.00",
    tags: ["air terjun", "malino"] },
  { name: "Bendungan Bili-bili", slug: "bendungan-bili-bili-gowa", category: "Danau", regency: "Gowa",
    description: "Bendungan yang juga jadi tempat wisata dengan pemandangan air jernih saat kemarau dan bebatuan eksotis di tepian danau.",
    location: { lat: -5.2333, lng: 119.6167 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp2.000 per orang", openHours: "06.00 - 18.00",
    tags: ["bendungan", "danau"] },
  { name: "Air Terjun Parangloe", slug: "air-terjun-parangloe-gowa", category: "Air Terjun", regency: "Gowa",
    description: "Air terjun bertingkat yang mengalir dari batuan berundak, memerlukan trekking sekitar 45-60 menit dari area parkir untuk mencapainya.",
    location: { lat: -5.2287, lng: 119.6631 } /* TERVERIFIKASI - koordinat GPS sumber wisataairterjun (5 13'43.47S 119 39'47.26E) */, entryFee: "Rp8.000 per orang", openHours: "07.00 - 17.00",
    tags: ["air terjun", "trekking"] },
  { name: "Danau Tanralili", slug: "danau-tanralili-gowa", category: "Danau", regency: "Gowa",
    description: "Danau vulkanik dengan air jernih dan tenang, dikelilingi perbukitan hijau, cocok untuk bersantai menikmati ketenangan alam.",
    location: { lat: -5.3500, lng: 119.8500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["danau", "vulkanik"] },
  { name: "Masjid Tua Al-Hilal Katangka", slug: "masjid-katangka-gowa", category: "Budaya/Sejarah", regency: "Gowa",
    description: "Salah satu masjid tertua di Sulawesi Selatan, peninggalan Kerajaan Gowa yang sarat nilai sejarah dan arsitektur khas.",
    location: { lat: -5.2167, lng: 119.4500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Gratis", openHours: "06.00 - 21.00",
    tags: ["masjid", "sejarah", "gowa"] },

  // ===== KOTA MAKASSAR =====
  { name: "Pantai Losari", slug: "pantai-losari-makassar", category: "Pantai", regency: "Kota Makassar",
    description: "Destinasi paling ikonik di Makassar untuk menikmati matahari terbenam sambil menikmati pisang epe khas kota ini di sepanjang promenade.",
    location: { lat: -5.1443, lng: 119.4081 } /* TERVERIFIKASI - Wikidata Q12502867 */, entryFee: "Gratis", openHours: "24 jam",
    tags: ["pantai", "losari", "sunset"] },
  { name: "Benteng Rotterdam", slug: "benteng-rotterdam-makassar", category: "Budaya/Sejarah", regency: "Kota Makassar",
    description: "Benteng peninggalan abad ke-17 yang memadukan arsitektur Eropa dan Bugis, kini berfungsi sebagai museum sejarah Makassar dan Kerajaan Gowa.",
    location: { lat: -5.1339, lng: 119.4103 } /* FIX BUG - sebelumnya identik dgn Pantai Losari. Jl. Ujung Pandang, Kel. Bulogading */, entryFee: "Rp5.000 per orang", openHours: "08.00 - 18.00",
    tags: ["benteng", "sejarah", "museum"] },
  { name: "Pulau Samalona", slug: "pulau-samalona-makassar", category: "Pulau", regency: "Kota Makassar",
    description: "Pulau tropis kecil berpasir putih dengan air jernih, sekitar 20-30 menit naik perahu dari pesisir kota, ideal untuk snorkeling singkat.",
    location: { lat: -5.1114, lng: 119.3606 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Sewa perahu, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["pulau", "snorkeling"] },
  { name: "Masjid 99 Kubah Al Alam", slug: "masjid-99-kubah-makassar", category: "Budaya/Sejarah", regency: "Kota Makassar",
    description: "Ikon arsitektur modern Makassar di kawasan Center Point of Indonesia, dengan 99 kubah yang bercahaya indah saat malam dan pemandangan laut.",
    location: { lat: -5.1325, lng: 119.4028 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Gratis", openHours: "06.00 - 21.00",
    tags: ["masjid", "arsitektur", "cpi"] },
  { name: "Trans Studio Makassar", slug: "trans-studio-makassar", category: "Taman/Kota", regency: "Kota Makassar",
    description: "Taman hiburan indoor terbesar di Indonesia timur dengan berbagai wahana seru untuk keluarga dan anak-anak.",
    location: { lat: -5.1667, lng: 119.4406 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Mulai Rp150.000 per orang", openHours: "10.00 - 21.00",
    tags: ["taman hiburan", "keluarga"] },
  { name: "Pantai Akkarena", slug: "pantai-akkarena-makassar", category: "Pantai", regency: "Kota Makassar",
    description: "Kawasan pantai modern dengan dermaga kayu, deretan restoran, dan pemandangan sunset romantis yang jadi favorit warga dan wisatawan.",
    location: { lat: -5.1685, lng: 119.4023 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp10.000 per orang", openHours: "10.00 - 22.00",
    tags: ["pantai", "kuliner", "sunset"] },

  // ===== MAROS =====
  { name: "Rammang-Rammang", slug: "rammang-rammang-maros", category: "Karst/Goa", regency: "Maros",
    description: "Kawasan karst megah dengan sungai tenang dan sawah hijau, aktivitas favorit menyusuri Sungai Pute dengan perahu jolloro menuju Kampung Berua.",
    location: { lat: -4.945, lng: 119.613 } /* Estimasi diperbaiki - Desa Salenrang, Kec. Bontoa, area dermaga */, entryFee: "Sewa perahu, mohon verifikasi ke pengelola", openHours: "07.00 - 17.00",
    tags: ["karst", "geopark", "perahu"] },
  { name: "Taman Nasional Bantimurung", slug: "tn-bantimurung-maros", category: "Air Terjun", regency: "Maros",
    description: "Dikenal sebagai 'The Kingdom of Butterflies', kawasan air terjun dengan ratusan spesies kupu-kupu dan gua prasejarah di sekitarnya.",
    location: { lat: -5.0671, lng: 119.6935 } /* TERVERIFIKASI - Wikipedia Simbang, Maros */, entryFee: "Rp15.000 per orang", openHours: "08.00 - 17.00",
    tags: ["air terjun", "kupu-kupu", "taman nasional"] },
  { name: "Taman Purbakala Leang-Leang", slug: "leang-leang-maros", category: "Karst/Goa", regency: "Maros",
    description: "Taman prasejarah dengan gua-gua berisi lukisan dinding purba berusia ribuan tahun di tengah kawasan karst yang menakjubkan.",
    location: { lat: -4.9833, lng: 119.6500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp15.000 per orang", openHours: "08.00 - 17.00",
    tags: ["gua", "prasejarah", "lukisan purba"] },
  { name: "Air Terjun Maddenge", slug: "air-terjun-maddenge-maros", category: "Air Terjun", regency: "Maros",
    description: "Air terjun unik yang terhimpit tebing bebatuan, incaran para fotografer karena panoramanya yang tersembunyi dan eksotis.",
    location: { lat: -4.9167, lng: 119.7500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "07.00 - 17.00",
    tags: ["air terjun", "fotografi"] },
  { name: "Permandian Air Panas Rea Toa", slug: "air-panas-rea-toa-maros", category: "Pegunungan", regency: "Maros",
    description: "Pemandian air panas alami dengan pemandangan pegunungan yang memberikan sensasi relaksasi berbeda dari tempat wisata lain di Maros.",
    location: { lat: -4.7500, lng: 119.8500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "07.00 - 18.00",
    tags: ["air panas", "relaksasi"] },

  // ===== TORAJA UTARA =====
  { name: "Londa", slug: "londa-toraja-utara", category: "Budaya/Sejarah", regency: "Toraja Utara",
    description: "Gua pemakaman alami berisi peti mati, tulang belulang, dan patung tau-tau leluhur Toraja yang tersusun di dinding tebing batu.",
    location: { lat: -3.0511, lng: 119.8583 } /* Estimasi diperbaiki - Desa Sendan Uai, Kec. Sanggalangi */, entryFee: "Rp10.000 per orang", openHours: "08.00 - 17.00",
    tags: ["makam", "budaya", "toraja"] },
  { name: "Danau Limbong", slug: "danau-limbong-toraja-utara", category: "Danau", regency: "Toraja Utara",
    description: "Danau tersembunyi dengan aliran sungai hijau dikelilingi pegunungan, memberikan kesan alami dan asri di Kecamatan Rantepao.",
    location: { lat: -2.9333, lng: 119.8833 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp10.000 domestik / Rp20.000 mancanegara", openHours: "07.00 - 17.00",
    tags: ["danau", "rantepao"] },
  { name: "Museum Ne' Gandeng", slug: "museum-ne-gandeng-toraja-utara", category: "Budaya/Sejarah", regency: "Toraja Utara",
    description: "Museum yang menyimpan koleksi benda bersejarah suku Toraja seperti batu menhir, patung Ne' Gandeng, dan gong belang.",
    location: { lat: -2.9000, lng: 119.8500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp10.000 domestik / Rp20.000 mancanegara", openHours: "08.00 - 17.00",
    tags: ["museum", "budaya"] },
  { name: "Bukit Singki", slug: "bukit-singki-toraja-utara", category: "Pegunungan", regency: "Toraja Utara",
    description: "Bukit dengan salib raksasa setinggi 30 meter, jadi tujuan wisata religi umat Kristiani dan spot terbaik memandang Kota Rantepao.",
    location: { lat: -2.9667, lng: 119.8833 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["religi", "pemandangan"] },
  { name: "Batutumonga", slug: "batutumonga-toraja-utara", category: "Pegunungan", regency: "Toraja Utara",
    description: "Wilayah tertinggi di lereng Gunung Sesean dengan pemandangan perkebunan dan sawah hijau terhampar luas, populer untuk menikmati sunrise.",
    location: { lat: -2.8833, lng: 119.8333 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "24 jam",
    tags: ["pegunungan", "sunrise", "sesean"] },

  // ===== TANA TORAJA =====
  { name: "Lembah Kendenan", slug: "lembah-kendenan-tana-toraja", category: "Pegunungan", regency: "Tana Toraja",
    description: "Lembah bak dataran tinggi Swiss dengan pemandangan perbukitan hijau membentang, suasana makin syahdu saat kabut turun menyelimuti lembah.",
    location: { lat: -3.2500, lng: 119.7500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["lembah", "pegunungan"] },
  { name: "Makam Lemo", slug: "makam-lemo-tana-toraja", category: "Budaya/Sejarah", regency: "Tana Toraja",
    description: "Kompleks pemakaman kuno di tebing batu dengan deretan patung tau-tau yang menjaga makam para leluhur Toraja.",
    location: { lat: -3.0750, lng: 119.8000 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp15.000 per orang", openHours: "08.00 - 17.00",
    tags: ["makam", "tau-tau", "budaya"] },
  { name: "Suaya", slug: "suaya-tana-toraja", category: "Budaya/Sejarah", regency: "Tana Toraja",
    description: "Kompleks makam keluarga bangsawan Toraja di Kecamatan Sangalla, dengan deretan patung tau-tau yang menjaga makam di tebing batu.",
    location: { lat: -3.1167, lng: 119.8500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "08.00 - 17.00",
    tags: ["makam", "sangalla"] },
  { name: "Buntu Burake", slug: "buntu-burake-tana-toraja", category: "Budaya/Sejarah", regency: "Tana Toraja",
    description: "Bukit dengan patung Yesus raksasa dan pemandangan Kota Makale dari ketinggian, jadi ikon wisata religi sekaligus spot foto populer.",
    location: { lat: -3.0136, lng: 119.8494 } /* Estimasi diperbaiki - bukit di atas Makale */, entryFee: "Rp10.000 per orang", openHours: "07.00 - 18.00",
    tags: ["religi", "patung", "makale"] },

  // ===== PANGKAJENE DAN KEPULAUAN =====
  { name: "Taman Purbakala Sumpang Bita", slug: "sumpang-bita-pangkep", category: "Karst/Goa", regency: "Pangkajene dan Kepulauan",
    description: "Bagian dari Geopark Maros-Pangkep dengan dua gua bersejarah, Leang Sumpang Bita (gua terbesar di Sulsel) dan Leang Bulu Sumi.",
    location: { lat: -4.8500, lng: 119.5500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp10.000 per orang", openHours: "08.00 - 17.00",
    tags: ["gua", "prasejarah", "geopark"] },
  { name: "Leang Lonrong", slug: "leang-lonrong-pangkep", category: "Karst/Goa", regency: "Pangkajene dan Kepulauan",
    description: "Pemandian alami dengan gua sungai bawah tanah berisi stalaktit dan stalagmit di kawasan karst Taman Nasional Bantimurung Bulusaraung.",
    location: { lat: -4.7000, lng: 119.6500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "07.00 - 17.00",
    tags: ["gua", "pemandian"] },
  { name: "Air Terjun Cambang Cui", slug: "air-terjun-cambang-cui-pangkep", category: "Air Terjun", regency: "Pangkajene dan Kepulauan",
    description: "Air terjun setinggi 5 meter di kaki Gunung Bulu Saraung dengan suasana tenang di antara pepohonan hijau yang segar.",
    location: { lat: -4.7500, lng: 119.5500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "07.00 - 17.00",
    tags: ["air terjun", "bulu saraung"] },
  { name: "Bulu Sorongan", slug: "bulu-sorongan-pangkep", category: "Pegunungan", regency: "Pangkajene dan Kepulauan",
    description: "Bukit dengan ketinggian 731 mdpl, favorit untuk hiking dengan pemandangan hijau yang memukau dari puncaknya.",
    location: { lat: -4.6500, lng: 119.6000 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["hiking", "bukit"] },
  { name: "Pulau Camba-Cambang", slug: "pulau-camba-cambang-pangkep", category: "Pulau", regency: "Pangkajene dan Kepulauan",
    description: "Pulau terdekat dari Pangkep dengan penginapan kecil bagi wisatawan, diakses lewat Dermaga Maccini Baji Labakkang.",
    location: { lat: -4.7500, lng: 119.3500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp10.000 per orang + sewa perahu", openHours: "06.00 - 18.00",
    tags: ["pulau", "penginapan"] },

  // ===== BANTAENG =====
  { name: "Pantai Marina Bantaeng", slug: "pantai-marina-bantaeng", category: "Pantai", regency: "Bantaeng",
    description: "Kawasan pantai keluarga di Desa Baruga, Pa'Jukukang, populer untuk rekreasi santai dengan suasana pesisir yang teduh.",
    location: { lat: -5.5500, lng: 119.9500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["pantai", "keluarga"] },
  { name: "Air Terjun Bissappu", slug: "air-terjun-bissappu-bantaeng", category: "Air Terjun", regency: "Bantaeng",
    description: "Air terjun setinggi sekitar 80 meter dengan panorama spektakuler, dikelilingi pepohonan hijau dan tebing berbatu, fasilitas sudah direnovasi baik.",
    location: { lat: -5.4500, lng: 119.9800 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "07.00 - 17.00",
    tags: ["air terjun", "bissappu"] },
  { name: "Bukit Rumbia", slug: "bukit-rumbia-bantaeng", category: "Pegunungan", regency: "Bantaeng",
    description: "Bukit dengan hamparan rumput hijau luas, tempat favorit untuk bersantai dan melepas penat di bawah pohon besar.",
    location: { lat: -5.4000, lng: 119.8500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["bukit", "rumbia"] },
  { name: "Rumah Adat Balla Lompoa Bantaeng", slug: "balla-lompoa-bantaeng", category: "Budaya/Sejarah", regency: "Bantaeng",
    description: "Rumah adat peninggalan tahun 1880 dengan arsitektur atap perahu terbalik, dulunya tempat tinggal para raja Bantaeng.",
    location: { lat: -5.54, lng: 119.96 } /* FIX BUG - sebelumnya identik dgn Pantai Seruni (file lain). Estimasi pusat Bantaeng. TODO verifikasi */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "08.00 - 17.00",
    tags: ["rumah adat", "sejarah"] },

  // ===== JENEPONTO =====
  { name: "Pantai Tamarunang", slug: "pantai-tamarunang-jeneponto", category: "Pantai", regency: "Jeneponto",
    description: "Sering disebut mirip Pantai Losari, menawarkan suasana tenang untuk healing dengan pemandangan sunset yang indah.",
    location: { lat: -5.6667, lng: 119.7500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "24 jam",
    tags: ["pantai", "sunset"] },
  { name: "Pantai Garassikang", slug: "pantai-garassikang-jeneponto", category: "Pantai", regency: "Jeneponto",
    description: "Pantai dengan gugusan batu karang dan tebing yang eksotis, cocok untuk fotografi meski akses jalannya masih sempit.",
    location: { lat: -5.6167, lng: 119.5500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["pantai", "karang", "fotografi"] },
  { name: "Air Terjun Tama'lulua", slug: "air-terjun-tamalulua-jeneponto", category: "Air Terjun", regency: "Jeneponto",
    description: "Dikenal juga sebagai Air Terjun Bossolo, jadi tujuan wisata utama bagi pecinta alam yang gemar trekking medan sulit.",
    location: { lat: -5.5500, lng: 119.6500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "07.00 - 17.00",
    tags: ["air terjun", "trekking"] },
  { name: "Pulau Libukang", slug: "pulau-libukang-jeneponto", category: "Pulau", regency: "Jeneponto",
    description: "Pulau seluas delapan hektar dengan pasir putih, air laut jernih, dan makam leluhur Puang Hawang yang masih diziarahi warga.",
    location: { lat: -5.5000, lng: 119.5500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp5.000 sewa perahu", openHours: "06.00 - 18.00",
    tags: ["pulau", "ziarah"] },
  { name: "Danau Bulu Jaya", slug: "danau-bulu-jaya-jeneponto", category: "Danau", regency: "Jeneponto",
    description: "Danau asri dengan air bersih di Kecamatan Bangkala Barat, dilihat dari perbukitan sekitarnya untuk pemandangan Jeneponto dari ketinggian.",
    location: { lat: -5.6500, lng: 119.5500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["danau", "bukit"] },

  // ===== WAJO =====
  { name: "Air Terjun Sumpang Puli", slug: "air-terjun-sumpang-puli-wajo", category: "Air Terjun", regency: "Wajo",
    description: "Hidden gem setinggi sekitar 30 meter di kawasan Pegunungan Keera, dikelilingi hutan alami dengan sumber air panas di dekatnya.",
    location: { lat: -3.8500, lng: 120.1500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp10.000 - Rp15.000 per orang", openHours: "07.00 - 17.00",
    tags: ["air terjun", "keera"] },
  { name: "Rumah Adat Attakkae", slug: "rumah-adat-attakkae-wajo", category: "Budaya/Sejarah", regency: "Wajo",
    description: "Kawasan rumah adat berisi Rumah Adat Saoraja Tenri Bali dengan 1.001 tiang penyangga seberat 2 ton tiap tiangnya, ikon budaya Bugis Wajo.",
    location: { lat: -4.128, lng: 120.005 } /* FIX BUG - sebelumnya identik dgn 2 destinasi Wajo lain. Estimasi area Sengkang. TODO verifikasi */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "08.00 - 17.00",
    tags: ["rumah adat", "budaya bugis"] },
  { name: "Museum Saoraja Mallangga", slug: "museum-saoraja-mallangga-wajo", category: "Budaya/Sejarah", regency: "Wajo",
    description: "Bekas kediaman raja dan pusat pemerintahan Wajo, kini jadi museum yang menyimpan koleksi benda bersejarah dan replika peninggalan kerajaan.",
    location: { lat: -4.135, lng: 120.02 } /* FIX BUG - sebelumnya identik dgn 2 destinasi Wajo lain. Estimasi area Sengkang. TODO verifikasi */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "08.00 - 16.00",
    tags: ["museum", "sengkang"] },
  { name: "Masjid Agung Ummul Qura", slug: "masjid-ummul-qura-wajo", category: "Budaya/Sejarah", regency: "Wajo",
    description: "Masjid ikon Kabupaten Wajo yang dibangun tahun 1964 dengan peletakan batu pertama oleh Presiden Soekarno, populer untuk wisata religi.",
    location: { lat: -4.14, lng: 120.01 } /* FIX BUG - sebelumnya identik dgn 2 destinasi Wajo lain. Estimasi area Sengkang. TODO verifikasi */, entryFee: "Gratis", openHours: "24 jam",
    tags: ["masjid", "religi", "sengkang"] },
  { name: "Desa Sutera Pakkana", slug: "desa-sutera-pakkana-wajo", category: "Budaya/Sejarah", regency: "Wajo",
    description: "Perkampungan pusat produksi sutera khas Wajo tempat wisatawan bisa menyaksikan proses pemintalan hingga penenunan kain sutera.",
    location: { lat: -4.0500, lng: 120.0000 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "08.00 - 17.00",
    tags: ["sutera", "kerajinan", "budaya"] },

  // ===== SOPPENG =====
  { name: "Pemandian Air Panas Lejja", slug: "air-panas-lejja-soppeng", category: "Pegunungan", regency: "Soppeng",
    description: "Pemandian air panas alami dengan suhu sekitar 60 derajat celcius, dipercaya dapat merilekskan diri di Desa Bulue, Marioriawa.",
    location: { lat: -4.2500, lng: 119.9500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp10.000 - Rp12.500 per orang", openHours: "07.00 - 18.00",
    tags: ["air panas", "relaksasi"] },
  { name: "Puncak Gunung Sewo", slug: "puncak-gunung-sewo-soppeng", category: "Pegunungan", regency: "Soppeng",
    description: "Puncak di ketinggian 450 mdpl di tengah kota, favorit untuk camping dan mendaki sambil menikmati pemandangan Kota Soppeng.",
    location: { lat: -4.3500, lng: 119.9000 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "24 jam",
    tags: ["gunung", "camping"] },
  { name: "Rumah Adat Sao Mario", slug: "rumah-adat-sao-mario-soppeng", category: "Budaya/Sejarah", regency: "Soppeng",
    description: "Kompleks rumah adat bergaya Bugis, Makassar, Mandar, Toraja, Minangkabau hingga Batak yang berfungsi sebagai museum benda antik.",
    location: { lat: -4.355, lng: 119.905 } /* FIX BUG - sebelumnya identik dgn Air Panas Lejja. Estimasi area Watansoppeng. TODO verifikasi */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "08.00 - 17.00",
    tags: ["rumah adat", "museum"] },
  { name: "Pemandian Alam Ompo", slug: "pemandian-ompo-soppeng", category: "Pegunungan", regency: "Soppeng",
    description: "Kolam alami dengan air sangat jernih dan dingin, jadi sumber air bersih warga sekaligus objek wisata andalan Soppeng.",
    location: { lat: -4.3200, lng: 119.9000 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["pemandian", "ompo"] },

  // ===== BONE =====
  { name: "Goa Mampu", slug: "goa-mampu-bone", category: "Karst/Goa", regency: "Bone",
    description: "Gua alam bersejarah dengan legenda kutukan kerajaan, menyimpan stalaktit dan stalagmit unik di Desa Cabbeng.",
    location: { lat: -4.4000, lng: 120.2000 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "08.00 - 17.00",
    tags: ["gua", "legenda"] },
  { name: "Puncak Lima Jari", slug: "puncak-lima-jari-bone", category: "Pegunungan", regency: "Bone",
    description: "Puncak dengan formasi ranting pohon membentuk lima jari, spot foto unik dengan latar hamparan pohon hijau di Kecamatan Ponre.",
    location: { lat: -4.5500, lng: 120.2500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Rp5.000 per orang", openHours: "06.00 - 18.00",
    tags: ["spot foto", "ponre"] },
  { name: "Hutan Pinus Bulu Tanah", slug: "hutan-pinus-bulu-tanah-bone", category: "Pegunungan", regency: "Bone",
    description: "Destinasi dataran tinggi bersuasana sejuk dan asri, favorit komunitas motor, pecinta alam, dan acara outdoor keluarga.",
    location: { lat: -4.3000, lng: 119.9000 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["hutan pinus", "outdoor"] },
  { name: "Bola Soba", slug: "bola-soba-bone", category: "Budaya/Sejarah", regency: "Bone",
    description: "Rumah bersejarah 'rumah persahabatan' peninggalan Raja-Raja Bone di Watampone, sering jadi lokasi tradisi lama masyarakat setempat.",
    location: { lat: -4.5333, lng: 120.3333 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Gratis", openHours: "08.00 - 17.00",
    tags: ["rumah adat", "sejarah", "watampone"] },
  { name: "Pantai Togeo Tonra", slug: "pantai-togeo-tonra-bone", category: "Pantai", regency: "Bone",
    description: "Pantai dengan laut biru jernih, pasir halus, dan deretan pohon kelapa rindang, alternatif suasana pantai selain Tanjung Pallette.",
    location: { lat: -4.9500, lng: 120.3500 } /* TODO: koordinat belum diverifikasi via pencarian - cek manual Google Maps */, entryFee: "Belum ada data, mohon verifikasi ke pengelola", openHours: "06.00 - 18.00",
    tags: ["pantai", "tonra"] }
]);
